name = input("이름을 입력하세요: ")
number = input("학번을 입력하세요: ")
major = input("학과를 입력하세요: ")
school = input("학교를 입력하세요: ")
year = input("학년을 입력하세요: ")

print()
print("<출력>")
print("이름:", name)
print("학번:", number)
print("학과:", major)
print("학교:", school)
print("학년:", year)